drop table `DbMysql07`.`CommentWordsPerSong`;
drop table `DbMysql07`.`Lyrics`;
drop table `DbMysql07`.`SongToArtist`;
drop table `DbMysql07`.`SongToCategory`;
drop table `DbMysql07`.`WordsPerSong`;
drop table `DbMysql07`.`Songs`;
drop table `DbMysql07`.`Artists`;
drop table `DbMysql07`.`Categories`;
drop table `DbMysql07`.`Comments`;